export type OrganizationForm = {
  name: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  state: string;
  postal_code: string;
  country: string;
  status: "active" | "inactive";
  website_url: string;
};

export type OrganizationEditForm = OrganizationForm & {
  business_name: string;
  description: string;
  logo: string | File;
  banner_image: string | File;
  primary_color: string;
  accent_color: string;
  gstin: string;
  fssai_license: string;
  enable_gst: boolean;
  cgst_rate: string;
  sgst_rate: string;
  service_charge_percentage: string;
  opening_time: string;
  closing_time: string;
  is_24_hours: boolean;
  holiday_mode: boolean;
  timezone: string;
  currency: string;
  cash_enabled: boolean;
  card_enabled: boolean;
  upi_enabled: boolean;
  wallet_enabled: boolean;
  online_payment_enabled: boolean;
  payment_gateway: string;
  enable_online_ordering: boolean;
  enable_table_booking: boolean;
  enable_dine_in: boolean;
  enable_takeaway: boolean;
  enable_delivery: boolean;
  delivery_radius: string;
  delivery_charge: string;
  minimum_order_value: string;
  free_delivery_above: string;
  enable_kot: boolean;
  enable_kds: boolean;
  auto_accept_orders: boolean;
  preparation_time_buffer: string;
  receipt_header: string;
  receipt_footer: string;
  alternate_phone: string;
  invoice_prefix: string;
};
