/**
 * This file is auto-generated by `npm run generate:api-types`.
 * Re-run when the FastAPI OpenAPI schema changes.
 *
 * OPENAPI_URL=http://localhost:8000/openapi.json npm run generate:api-types
 */

export type paths = Record<string, never>;

export type components = Record<string, never>;

export type operations = Record<string, never>;
