import {
    LayoutDashboard,
    ShoppingCart,
    BarChart3,
    Settings,
    Users,
    Package,
    ChefHat,
    FileText,
    Heart,
    Monitor,
    QrCode,
    Calendar,
    Building2,
    Layers3,
    GitBranch,
    Database,
    Workflow,
    Network,
    Shield,
    Globe,
    LayoutGrid,
} from "lucide-react";

export type UserRole = "super_admin" | "admin" | "supervisor" | "user";

export interface NavItem {
    name: string;
    href: string;
    icon: any;
    description: string;
    roles: UserRole[];
    category?: string;
}

export const navigationConfig: NavItem[] = [
    // Super Admin Specific
    {
        name: "System Overview",
        href: "/super-admin",
        icon: LayoutDashboard,
        description: "System Health & Metrics",
        roles: ["super_admin"],
        category: "overview",
    },
    {
        name: "Restaurant",
        href: "/super-admin/organizations",
        icon: Building2,
        description: "Restaurant Management",
        roles: ["super_admin"],
        category: "organizations",
    },
    {
        name: "Users",
        href: "/super-admin/users",
        icon: Users,
        description: "User & Role Management",
        roles: ["super_admin"],
        category: "configuration",
    },
    {
        name: "Category",
        href: "/super-admin/categories",
        icon: Layers3,
        description: "Category Management",
        roles: ["super_admin"],
        category: "configuration",
    },
    {
        name: "Product",
        href: "/super-admin/products?tab=products",
        icon: Package,
        description: "Product Management",
        roles: ["super_admin"],
        category: "configuration",
    },
    {
        name: "Modifiers",
        href: "/super-admin/products?tab=modifiers",
        icon: FileText,
        description: "Modifier Management",
        roles: ["super_admin"],
        category: "configuration",
    },
    {
        name: "Modifier Options",
        href: "/super-admin/modifier-options",
        icon: GitBranch,
        description: "Option Management",
        roles: ["super_admin"],
        category: "configuration",
    },
    {
        name: "Combo Product",
        href: "/super-admin/combos",
        icon: ChefHat,
        description: "Combo Product Management",
        roles: ["super_admin"],
        category: "configuration",
    },
    {
        name: "Tables",
        href: "/super-admin/tables",
        icon: Calendar,
        description: "Table Management",
        roles: ["super_admin"],
        category: "configuration",
    },
    {
        name: "Home Banners",
        href: "/super-admin/homebanners",
        icon: Globe,
        description: "Homepage Banner Management",
        roles: ["super_admin"],
        category: "configuration",
    },
    {
        name: "Row Management",
        href: "/super-admin/row-management",
        icon: LayoutGrid,
        description: "Homepage Rows & Sections",
        roles: ["super_admin"],
        category: "configuration",
    },
    {
        name: "Data Migration",
        href: "/super-admin/migration",
        icon: Database,
        description: "Transfer & Sync Systems",
        roles: ["super_admin"],
        category: "data",
    },
    {
        name: "Workflow Builder",
        href: "/super-admin/workflows",
        icon: Workflow,
        description: "Process Automation",
        roles: ["super_admin"],
        category: "automation",
    },
    {
        name: "Global Analytics",
        href: "/super-admin/analytics",
        icon: BarChart3,
        description: "Cross-System Reports",
        roles: ["super_admin"],
        category: "insights",
    },
    {
        name: "Network Config",
        href: "/super-admin/network",
        icon: Network,
        description: "API & Integrations",
        roles: ["super_admin"],
        category: "technical",
    },
    {
        name: "Security Center",
        href: "/super-admin/security",
        icon: Shield,
        description: "Access & Permissions",
        roles: ["super_admin"],
        category: "security",
    },
    {
        name: "Global Settings",
        href: "/super-admin/settings",
        icon: Settings,
        description: "System Configuration",
        roles: ["super_admin"],
        category: "settings",
    },

    // Regular Admin, Supervisor, User
    {
        name: "Dashboard",
        href: "/admin",
        icon: LayoutDashboard,
        description: "Overview & Quick Stats",
        roles: ["admin", "supervisor", "user"],
    },
    {
        name: "Order Terminal",
        href: "/admin/order",
        icon: ShoppingCart,
        description: "POS & Billing",
        roles: ["admin", "supervisor", "user"],
    },
    {
        name: "Kitchen Queue",
        href: "/admin/queue",
        icon: Monitor,
        description: "Live Order Queue",
        roles: ["admin", "supervisor", "user"],
    },
    {
        name: "Analytics",
        href: "/admin/analytics",
        icon: BarChart3,
        description: "Reports & Insights",
        roles: ["admin", "supervisor"],
    },
    {
        name: "Reports",
        href: "/admin/reports",
        icon: FileText,
        description: "Business Analytics",
        roles: ["admin", "supervisor"],
    },
    {
        name: "Category",
        href: "/admin/categories",
        icon: Layers3,
        description: "Category Management",
        roles: ["admin"],
    },
    {
        name: "Products",
        href: "/admin/products",
        icon: Package,
        description: "Menu & Inventory",
        roles: ["admin", "supervisor"],
    },
    {
        name: "Modifiers",
        href: "/admin/products?tab=modifiers",
        icon: FileText,
        description: "Modifier Management",
        roles: ["admin", "supervisor"],
    },
    {
        name: "Modifier Options",
        href: "/admin/modifier-options",
        icon: GitBranch,
        description: "Option Management",
        roles: ["admin", "supervisor", "user"],
    },
    {
        name: "Combos",
        href: "/admin/combos",
        icon: ChefHat,
        description: "Combo Products",
        roles: ["admin", "supervisor"],
    },
    {
        name: "Tax Rules",
        href: "/admin/tax",
        icon: FileText,
        description: "Tax Configuration",
        roles: ["admin"],
    },
    {
        name: "Customers",
        href: "/admin/customers",
        icon: Heart,
        description: "Customer & Loyalty",
        roles: ["admin", "supervisor"],
    },
    {
        name: "Home Banners",
        href: "/admin/homebanners",
        icon: Globe,
        description: "Homepage Banners",
        roles: ["admin", "supervisor"],
    },
    {
        name: "Row Management",
        href: "/admin/row-management",
        icon: LayoutGrid,
        description: "Homepage Rows & Sections",
        roles: ["admin", "supervisor"],
    },
    {
        name: "QR Orders",
        href: "/admin/qr-management",
        icon: QrCode,
        description: "QR Code & Tables",
        roles: ["admin", "supervisor"],
    },
    {
        name: "Table Booking",
        href: "/admin/table-booking",
        icon: Calendar,
        description: "Reservations & Tables",
        roles: ["admin", "supervisor", "user"],
    },
    {
        name: "Users",
        href: "/admin/users",
        icon: Users,
        description: "Staff & Roles",
        roles: ["admin"],
    },
    {
        name: "Settings",
        href: "/admin/settings",
        icon: Settings,
        description: "Configuration",
        roles: ["admin"],
    },
];

export const getNavigationForRole = (role: UserRole) => {
    return navigationConfig.filter((item) => item.roles.includes(role));
};
